### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by skoehler** [Froxlor/Gentoo-Ebuild#1]
Please update the ebuild to something recent. Current version seems to be 0.10.32.

**Comment by d00p** [comment]
Trying my best, need to setup a gentoo testing machine, @Dessa seems to be unavailable for this at the moment

**Comment by Dessa** [comment]
that is accurate, im still kind of stranded with broken hardware, maybe i can put together a pr but no promises. at least the required changes should be on the light side.

**Comment by skoehler** [comment]
froxlor pulls in php7 because all php8 ebuild lack the json USE flag. That's something that should be fixed. I believe, froxlor is php8 compatible now.

**Comment by d00p** [comment]
Hope i've not done too badly on this one...
